# IMPORTANT: Changes to this file will be applied to all environments, even if you deploy dev only.

---
apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: {{ project-name }}
  labels:
    p6m.dev/domain: '{{ organization-name }}'
    p6m.dev/app: '{{ project-name }}'
spec:
  autoscaling:
    enabled: true
  deployment:
    image: '{{ project-name }}-server:latest' # Set to a digest in the .platform repo patch
    ports:
      - protocol: http
        port: 3000
    readinessProbe:
      port: 3000
      path: /
  networking:
    ingress:
      enabled: true
      oidc: true # OAuth2 Proxy is enabled by default
      path: /
      hostnames: [] # This is set in the patch files per environment
